In [2]:
#Consider the below code to answer further questions:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)

In [3]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [5]:
type(list_)

list

In [6]:
type(array_list)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.


In [11]:
print("datatype of each element of list_:")
for i in list_:
    print(i,type(i))
print("datatype of each elemnet of array_list")
for j in array_list:
    print(j,type(j))

datatype of each element of list_:
1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>
datatype of each elemnet of array_list
1 <class 'numpy.str_'>
2 <class 'numpy.str_'>
3 <class 'numpy.str_'>
4 <class 'numpy.str_'>
5 <class 'numpy.str_'>


In [19]:
array_list = np.array(object = list_, dtype = int)

In [20]:
print("datatype of each element of list_:")
for i in list_:
    print(i,type(i))
print("datatype of each elemnet of array_list")
for j in array_list:
    print(j,type(j))

datatype of each element of list_:
1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>
datatype of each elemnet of array_list
1 <class 'numpy.int64'>
2 <class 'numpy.int64'>
3 <class 'numpy.int64'>
4 <class 'numpy.int64'>
5 <class 'numpy.int64'>


In [21]:
#Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [22]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
num_array.shape

(2, 3)

In [24]:
num_array.size

6

In [15]:
arr2=np.zeros((3,3))

In [16]:
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
arr2=np.identity(5)

In [18]:
arr2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr3=np.diag()